export const REDUX = {
    AUTHEN: {
        FAIL_AUTHEN: "FAIL_AUTHEN",
        EXACT_AUTHEN: "EXACT_AUTHEN",
    },
    PENDING_JOBS: {
        GET_PENDING_JOBS: "GET_PENDING_JOBS",
    },

    JOB_NAMES: {
        GET_JOB_NAMES: "GET_JOB_NAMES",
        GET_SINGLE_JOB_NAME: "GET_SINGLE_JOB_NAME"
    },

    TYPE_MANAGEMENT: {
        GET_TYPE_MANAGEMENT: "GET_TYPE_MANAGEMENT",
    },

    ANNOUNCEMENTS: {
        GET_ANNOUNCEMENTS: "GET_ANNOUNCEMENTS"
    },

    JOB_ANNOUNCEMENTS: {
        GET_JOB_ANNOUNCEMENTS: "JOB_ANNOUNCEMENTS"
    },

    ANNOUNCEMENT_DETAIL: {
        GET_ANNOUNCEMENT_DETAIL: "GET_ANNOUNCEMENT_DETAIL"
    },

    TYPE_SCHOOLS: {
        GET_TYPE_SCHOOLS: "GET_TYPE_SCHOOLS",
    },

    LANGUAGES: {
        GET_LANGUAGES: "GET_LANGUAGES"
    },

    REGIONS: {
        GET_REGIONS: "GET_REGIONS"
    },

    SKILLS: {
        GET_SKILLS: "GET_SKILLS"
    },

    MAJORS: {
        GET_MAJORS: "GET_MAJORS"
    },

    JOB_GROUPS: {
        GET_JOB_GROUPS: "GET_JOB_GROUPS"
    },

    BRANCHES: {
        GET_BRANCHES: "GET_BRANCHES"
    },

    EM_BRANCHES: {
        GET_EM_BRANCHES: "GET_EM_BRANCHES"
    },
};

export const REDUX_SAGA = {

    PENDING_JOBS: {
        GET_PENDING_JOBS: "GET_PENDING_JOBS_DATA",
    },

    JOB_NAMES: {
        GET_JOB_NAMES: "GET_JOB_NAMES_DATA",
    },

    TYPE_MANAGEMENT: {
        GET_TYPE_MANAGEMENT: "GET_TYPE_MANAGEMENT_DATA",
    },

    ANNOUNCEMENTS: {
        GET_ANNOUNCEMENTS: "GET_ANNOUNCEMENTS_DATA"
    },

    ANNOUNCEMENT_DETAIL: {
        GET_ANNOUNCEMENT_DETAIL: "GET_ANNOUNCEMENT_DETAIL_DATA"
    },

    TYPE_SCHOOLS: {
        GET_TYPE_SCHOOLS: "GET_TYPE_SCHOOLS_DATA",

    },

    LANGUAGES: {
        GET_LANGUAGES: "GET_LANGUAGES_DATA"
    },

    REGIONS: {
        GET_REGIONS: "GET_REGIONS_DATA"
    },

    SKILLS: {
        GET_SKILLS: "GET_SKILLS_DATA"
    },

    MAJORS: {
        GET_MAJORS: "GET_MAJORS_DATA"
    },

    JOB_GROUPS: {
        GET_JOB_GROUPS: "GET_JOB_GROUPS_DATA"
    },

    BRANCHES: {
        GET_BRANCHES: "GET_BRANCHES_DATA"
    },

    JOB_ANNOUNCEMENTS: {
        GET_JOB_ANNOUNCEMENTS: "JOB_ANNOUNCEMENTS_DATA"
    },

    EM_BRANCHES: {
        GET_EM_BRANCHES: "GET_EM_BRANCHES_DATA"
    },
}