export const REDUX = {
    AUTHEN: {
        FAIL_AUTHEN: "FAIL_AUTHEN",
        EXACT_AUTHEN: "EXACT_AUTHEN",
    },
    PENDING_JOBS: {
        GET_PENDING_JOBS: "GET_PENDING_JOBS",
    },
    JOB_NAMES: {
        GET_JOB_NAMES: "GET_JOB_NAMES",
        GET_SINGLE_JOB_NAME: "GET_SINGLE_JOB_NAME"
    },
    TYPE_MANAGEMENT: {
        GET_TYPE_MANAGEMENT: "GET_TYPE_MANAGEMENT",
    },
    JOB_ANNOUNCEMENTS: {
        GET_JOB_ANNOUNCEMENTS: "GET_JOB_ANNOUNCEMENTS"
    },
    TYPE_SCHOOLS: {
        GET_TYPE_SCHOOLS: "GET_TYPE_SCHOOLS",
    },
    LANGUAGES: {
        GET_LANGUAGES: "GET_LANGUAGES"
    },
    REGIONS: {
        GET_REGIONS: "GET_REGIONS"
    },
    SKILLS: {
        GET_SKILLS: "GET_SKILLS"
    },
    MAJORS: {
        GET_MAJORS: "GET_MAJORS"
    },
    JOB_GROUPS: {
        GET_JOB_GROUPS: "GET_JOB_GROUPS"
    },
    BRANCHES: {
        GET_BRANCHES: "GET_BRANCHES"
    },
    EM_BRANCHES: {
        GET_EM_BRANCHES: "GET_EM_BRANCHES"
    },
    ANNOU_COMMENTS: {
        GET_ANNOU_COMMENTS: "GET_ANNOU_COMMENTS",
    },
    ANNOU_TYPES: {
        GET_ANNOU_TYPES: "GET_ANNOU_TYPES",
    },
    ANNOUNCEMENTS: {
        GET_ANNOUNCEMENTS: "GET_ANNOUNCEMENTS"
    },
    ANNOUNCEMENT_DETAIL: {
        GET_ANNOUNCEMENT_DETAIL: "GET_ANNOUNCEMENT_DETAIL"
    },
    JOB_ANNOUNCEMENT_DETAIL: {
        GET_JOB_ANNOUNCEMENT_DETAIL: "GET_JOB_ANNOUNCEMENT_DETAIL"
    },
    FIND_CANDIDATES: {
        GET_FIND_CANDIDATES: "GET_FIND_CANDIDATES"
    },
    FIND_CANDIDATE_DETAIL: {
        GET_FIND_CANDIDATE_DETAIL: "GET_FIND_CANDIDATE_DETAIL"
    },
    SAVED_CANDIDATE_PROFILES: {
        GET_SAVED_CANDIDATE_PROFILES: "GET_SAVED_CANDIDATE_PROFILES"
    },
    SAVED_CANDIDATE_PROFILE_DETAIL: {
        GET_SAVED_CANDIDATE_PROFILE_DETAIL: "GET_SAVED_CANDIDATE_PROFILE_DETAIL"
    },
    JOB_SERVICE: {
        GET_JOB_SERVICE: "GET_JOB_SERVICE"
    }
};

export const REDUX_SAGA = {
    PENDING_JOBS: {
        GET_PENDING_JOBS: "GET_PENDING_JOBS_DATA",
    },
    JOB_NAMES: {
        GET_JOB_NAMES: "GET_JOB_NAMES_DATA",
    },
    TYPE_MANAGEMENT: {
        GET_TYPE_MANAGEMENT: "GET_TYPE_MANAGEMENT_DATA",
    },
    TYPE_SCHOOLS: {
        GET_TYPE_SCHOOLS: "GET_TYPE_SCHOOLS_DATA",

    },
    LANGUAGES: {
        GET_LANGUAGES: "GET_LANGUAGES_DATA"
    },
    REGIONS: {
        GET_REGIONS: "GET_REGIONS_DATA"
    },
    SKILLS: {
        GET_SKILLS: "GET_SKILLS_DATA"
    },
    MAJORS: {
        GET_MAJORS: "GET_MAJORS_DATA"
    },
    JOB_GROUPS: {
        GET_JOB_GROUPS: "GET_JOB_GROUPS_DATA"
    },
    BRANCHES: {
        GET_BRANCHES: "GET_BRANCHES_DATA"
    },
    JOB_ANNOUNCEMENTS: {
        GET_JOB_ANNOUNCEMENTS: "GET_JOB_ANNOUNCEMENTS_DATA"
    },
    EM_BRANCHES: {
        GET_EM_BRANCHES: "GET_EM_BRANCHES_DATA"
    },
    ANNOU_TYPES: {
        GET_ANNOU_TYPES: "GET_ANNOU_TYPES_DATA",
    },

    ANNOU_COMMENTS: {
        GET_ANNOU_COMMENTS: "GET_ANNOU_COMMENTS_DATA",
    },

    ANNOUNCEMENTS: {
        GET_ANNOUNCEMENTS: "GET_ANNOUNCEMENTS_DATA"
    },
    ANNOUNCEMENT_DETAIL: {
        GET_ANNOUNCEMENT_DETAIL: "GET_ANNOUNCEMENT_DETAIL_DATA"
    },
    FIND_CANDIDATES: {
        GET_FIND_CANDIDATES: "GET_FIND_CANDIDATES_DATA"
    },
    FIND_CANDIDATE_DETAIL: {
        GET_FIND_CANDIDATE_DETAIL: "GET_FIND_CANDIDATE_DETAIL_DATA"
    },
    SAVED_CANDIDATE_PROFILES: {
        GET_SAVED_CANDIDATE_PROFILES: "GET_SAVED_CANDIDATE_PROFILES_DATA"
    },
    SAVED_CANDIDATE_PROFILE_DETAIL: {
        GET_SAVED_CANDIDATE_PROFILE_DETAIL: "GET_SAVED_CANDIDATE_PROFILE_DETAIL_DATA"
    },
    JOB_ANNOUNCEMENT_DETAIL: {
        GET_JOB_ANNOUNCEMENT_DETAIL: "GET_JOB_ANNOUNCEMENT_DETAIL_DATA"
    },
    JOB_SERVICE: {
        GET_JOB_SERVICE: "GET_JOB_SERVICE_DATA"
    }
}