export const OAUTH2_LOGIN = "/api/authentication/username-password";
export const EMPLOYER_REGISTER = "/api/employers/registration/email";
export const REGIONS = "/api/regions";
export const LANGUAGES = "/api/languages";
export const JOB_NAMES = "/api/jobNames";
export const RE_PASSWORD = "/api/users/password/new";
export const ANNOU_TYPES_PUBLIC = "/api/announcementTypes";
export const ANNOU_PUBLIC = "/api/announcements";
export const SCHOOL = "/api/schools";
export const RFGTK= "/api/authentication/refresh-token"
export const RSPW= "/api/users/password/reset";
export const SMRQ = '/api/users/password/new'
export const M_S = '/api/users/password/reset/request';
export const JOB_SUITABLE_CANDIDATE = '/api/employers/{id}/candidates/recommended';
